// related to auth
export const PARENT_REGISTER_REQUEST = 'PARENT_REGISTER_REQUEST'
export const PARENT_REGISTER_SUCCESS = 'PARENT_REGISTER_SUCCESS'
export const PARENT_REGISTER_FAIL = 'PARENT_REGISTER_FAIL'

export const PARENT_LOGIN_REQUEST = 'PARENT_LOGIN_REQUEST'
export const PARENT_LOGIN_SUCCESS = 'PARENT_LOGIN_SUCCESS'
export const PARENT_LOGIN_FAIL = 'PARENT_LOGIN_FAIL'

export const PARENT_LOGOUT = 'PARENT_LOGOUT'

export const PARENT_UPDATE = 'PARENT_UPDATE'

export const PARENT_READ_LS = 'PARENT_READ_LS'

// add student (and delete addStudent)
export const PARENT_ADD_STUDENT_REQUEST = 'PARENT_ADD_STUDENT_REQUEST'
export const PARENT_ADD_STUDENT_SUCCESS = 'PARENT_ADD_STUDENT_SUCCESS'
export const PARENT_ADD_STUDENT_FAIL = 'PARENT_ADD_STUDENT_FAIL'
export const PARENT_ADD_STUDENT_DELETE = 'PARENT_ADD_STUDENT_DELETE'

// get marks (and delete marks)
export const PARENT_MARKS_REQUEST = 'PARENT_MARKS_REQUEST'
export const PARENT_MARKS_SUCCESS = 'PARENT_MARKS_SUCCESS'
export const PARENT_MARKS_FAIL = 'PARENT_MARKS_FAIL'
export const PARENT_MARKS_DELETE = 'PARENT_MARKS_DELETE'

// get truancys (and delete truancys)
export const PARENT_TRUANCYS_REQUEST = 'PARENT_TRUANCYS_REQUEST'
export const PARENT_TRUANCYS_SUCCESS = 'PARENT_TRUANCYS_SUCCESS'
export const PARENT_TRUANCYS_FAIL = 'PARENT_TRUANCYS_FAIL'
export const PARENT_TRUANCYS_DELETE = 'PARENT_TRUANCYS_DELETE'

// get average marks
export const PARENT_AVERAGE_MARKS_REQUEST =
  'PARENT_AVERAGE_MARKS_REQUEST'
export const PARENT_AVERAGE_MARKS_SUCCESS =
  'PARENT_AVERAGE_MARKS_SUCCESS'
export const PARENT_AVERAGE_MARKS_FAIL = 'PARENT_AVERAGE_MARKS_FAIL'

// get term marks
export const PARENT_TERM_MARKS_REQUEST = 'PARENT_TERM_MARKS_REQUEST'
export const PARENT_TERM_MARKS_SUCCESS = 'PARENT_TERM_MARKS_SUCCESS'
export const PARENT_TERM_MARKS_FAIL = 'PARENT_TERM_MARKS_FAIL'

export const PARENT_FINAL_MARKS_REQUEST = 'PARENT_FINAL_MARKS_REQUEST'
export const PARENT_FINAL_MARKS_SUCCESS = 'PARENT_FINAL_MARKS_SUCCESS'
export const PARENT_FINAL_MARKS_FAIL = 'PARENT_FINAL_MARKS_FAIL'

export const PARENT_STUDENT_TIMETABLE_REQUEST =
  'PARENT_STUDENT_TIMETABLE_REQUEST'
export const PARENT_STUDENT_TIMETABLE_SUCCESS =
  'PARENT_STUDENT_TIMETABLE_SUCCESS'
export const PARENT_STUDENT_TIMETABLE_FAIL =
  'PARENT_STUDENT_TIMETABLE_FAIL'

export const PARENT_STUDENT_TIMETABLE_TEACHERS_REQUEST =
  'PARENT_STUDENT_TIMETABLE_TEACHERS_REQUEST'
export const PARENT_STUDENT_TIMETABLE_TEACHERS_SUCCESS =
  'PARENT_STUDENT_TIMETABLE_TEACHERS_SUCCESS'
export const PARENT_STUDENT_TIMETABLE_TEACHERS_FAIL =
  'PARENT_STUDENT_TIMETABLE_TEACHERS_FAIL'

export const PARENT_STUDENT_SCHOOL_REQUEST =
  'PARENT_STUDENT_SCHOOL_REQUEST'
export const PARENT_STUDENT_SCHOOL_SUCCESS =
  'PARENT_STUDENT_SCHOOL_SUCCESS'
export const PARENT_STUDENT_SCHOOL_FAIL = 'PARENT_STUDENT_SCHOOL_FAIL'
